In [1]:
import numpy as np
import scipy as sp

In [36]:
 np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

# Construct $J_{ij}$ for some choice of pattern vectors

In [35]:
xi_1 = [1, 1, 1]
xi_2 = [1, -1, -1]
xi_matrix = np.array([xi_1, xi_2]).T
print(xi_matrix)

[[ 1  1]
 [ 1 -1]
 [ 1 -1]]


In [15]:
N, p = xi_matrix.shape
print(N, p)

3 2


In [12]:
A_matrix = xi_matrix.T @ xi_matrix
print(A_matrix)

[[ 3 -1]
 [-1  3]]


In [13]:
A_inverse = np.linalg.inv(A_matrix)
print(A_inverse)

[[0.375 0.125]
 [0.125 0.375]]


In [24]:
J_matrix = xi_matrix @ A_inverse @ xi_matrix.T
print(J_matrix)

[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [26]:
J_matrix_hollowed = J_matrix - np.diag(np.diag(J_matrix))
print(J_matrix_hollowed)

[[0.  0.  0. ]
 [0.  0.  0.5]
 [0.  0.5 0. ]]


# Eigenvalues and eigenvectors for $\bf{J}$

In [25]:
w, v = np.linalg.eig(J_matrix)

In [19]:
w

array([1.00000000e+00, 1.11022302e-16, 1.00000000e+00])

In [20]:
v

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ]])

In [21]:
J_matrix @ xi_1

array([1., 1., 1.])

In [22]:
J_matrix @ xi_2

array([ 1., -1., -1.])

# Eigenvalues and eigenvectors for $\bf{J'}$ with $J_{ii}$ set to $0$

In [27]:
w_prime, v_prime = np.linalg.eig(J_matrix_hollowed)

In [28]:
w_prime

array([ 0.5, -0.5,  0. ])

In [30]:
v_prime

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.70710678, -0.70710678,  0.        ]])

In [33]:
J_matrix_hollowed @ xi_1

array([0. , 0.5, 0.5])

In [34]:
J_matrix_hollowed @ xi_2

array([ 0. , -0.5, -0.5])