In [2]:
import numpy as np
import scipy as sp

In [3]:
 np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

# Construct $J_{ij}$ for some choice of pattern vectors

In [4]:
xi_1 = [1,   1,  1, -1, -1, -1, -1, -1, -1]
xi_2 = [-1, -1, -1,  1,  1,  1, -1, -1, -1]
xi_3 = [-1, -1, -1, -1, -1, -1,  1,  1 , 1]
xi_matrix = np.array([xi_1, xi_2, xi_3]).T
print(xi_matrix)

[[ 1 -1 -1]
 [ 1 -1 -1]
 [ 1 -1 -1]
 [-1  1 -1]
 [-1  1 -1]
 [-1  1 -1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]]


In [5]:
N, p = xi_matrix.shape
print(N, p)

9 3


In [6]:
A_matrix = xi_matrix.T @ xi_matrix
print(A_matrix)

[[ 9 -3 -3]
 [-3  9 -3]
 [-3 -3  9]]


In [7]:
A_inverse = np.linalg.inv(A_matrix)
print(A_inverse)

[[0.167 0.083 0.083]
 [0.083 0.167 0.083]
 [0.083 0.083 0.167]]


In [8]:
J_matrix = xi_matrix @ A_inverse @ xi_matrix.T
print(J_matrix)

[[0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.333 0.333 0.333 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.333 0.333 0.333 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.333 0.333 0.333 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.333 0.333]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.333 0.333]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.333 0.333]]


In [9]:
J_matrix_hollowed = J_matrix - np.diag(np.diag(J_matrix))
print(J_matrix_hollowed)

[[0.000 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.000 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.333 0.333 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.333 0.000 0.333 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.333 0.333 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.333]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.000 0.333]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.333 0.333 0.000]]


# Eigenvalues and eigenvectors for $\bf{J}$

In [10]:
w, v = np.linalg.eig(J_matrix)

In [11]:
w

array([1.000, 0.000, 0.000, 1.000, 0.000, 0.000, 1.000, -0.000, 0.000])

In [12]:
v

array([[-0.577, -0.000, -0.667, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [-0.577, -0.707, -0.075, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [-0.577, 0.707, 0.742, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.577, -0.000, -0.667, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.577, -0.707, -0.075, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.577, 0.707, 0.742, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.577, 0.000, -0.521],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.577, -0.707, -0.284],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.577, 0.707, 0.805]])

In [36]:
J_matrix @ xi_1

array([1.000, 1.000, 1.000, -1.000, -1.000, -1.000, -1.000, -1.000,
       -1.000])

In [37]:
J_matrix @ xi_2

array([-1.000, -1.000, -1.000, 1.000, 1.000, 1.000, -1.000, -1.000,
       -1.000])

In [38]:
J_matrix @ xi_3

array([-1.000, -1.000, -1.000, -1.000, -1.000, -1.000, 1.000, 1.000,
       1.000])

# Eigenvalues and eigenvectors for $\bf{J'}$ with $J_{ii}$ set to $0$

In [15]:
w_prime, v_prime = np.linalg.eig(J_matrix_hollowed)

In [16]:
w_prime

array([-0.333, 0.667, -0.333, -0.333, 0.667, -0.333, -0.333, 0.667,
       -0.333])

In [17]:
v_prime

array([[-0.816, 0.577, 0.201, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.408, 0.577, -0.786, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.408, 0.577, 0.585, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.816, 0.577, 0.201, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.408, 0.577, -0.786, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.408, 0.577, 0.585, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, -0.816, 0.577, -0.144],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.408, 0.577, -0.624],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.408, 0.577, 0.768]])

In [41]:
J_matrix_hollowed @ xi_1 

array([0.667, 0.667, 0.667, -0.667, -0.667, -0.667, -0.667, -0.667,
       -0.667])

In [40]:
J_matrix_hollowed @ xi_2

array([-0.667, -0.667, -0.667, 0.667, 0.667, 0.667, -0.667, -0.667,
       -0.667])

In [39]:
J_matrix_hollowed @ xi_3

array([-0.667, -0.667, -0.667, -0.667, -0.667, -0.667, 0.667, 0.667,
       0.667])