In [3]:
import numpy as np
import scipy as sp

In [20]:
 np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

# Construct $J_{ij}$ for some choice of pattern vectors

In [21]:
xi_1 = [1, 1, 1, 1, 1, 1, 1, 1, 1]
xi_2 = [1, 1, 1, -1, -1, -1, -1, -1, -1]
xi_matrix = np.array([xi_1, xi_2]).T
print(xi_matrix)

[[ 1  1]
 [ 1  1]
 [ 1  1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]
 [ 1 -1]]


In [22]:
N, p = xi_matrix.shape
print(N, p)

9 2


In [23]:
A_matrix = xi_matrix.T @ xi_matrix
print(A_matrix)

[[ 9 -3]
 [-3  9]]


In [24]:
A_inverse = np.linalg.inv(A_matrix)
print(A_inverse)

[[0.125 0.042]
 [0.042 0.125]]


In [25]:
J_matrix = xi_matrix @ A_inverse @ xi_matrix.T
print(J_matrix)

[[0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.167]]


In [26]:
J_matrix_hollowed = J_matrix - np.diag(np.diag(J_matrix))
print(J_matrix_hollowed)

[[0.000 0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.000 0.333 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.333 0.333 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.000 0.167 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.000 0.167 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.000 0.167 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.000 0.167]
 [0.000 0.000 0.000 0.167 0.167 0.167 0.167 0.167 0.000]]


# Eigenvalues and eigenvectors for $\bf{J}$

In [27]:
w, v = np.linalg.eig(J_matrix)

In [28]:
w

array([1.000, 0.000, 0.000, 1.000, -0.000, 0.000, 0.000, 0.000, 0.000])

In [29]:
v

array([[-0.577, -0.000, -0.667, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [-0.577, -0.707, -0.075, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [-0.577, 0.707, 0.742, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.408, -0.000, 0.445, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.408, -0.894, -0.870, -0.000, -0.000,
        -0.000],
       [0.000, 0.000, 0.000, -0.408, 0.224, 0.106, -0.289, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.408, 0.224, 0.106, -0.289, -0.408,
        -0.717],
       [0.000, 0.000, 0.000, -0.408, 0.224, 0.106, -0.289, -0.408, 0.021],
       [0.000, 0.000, 0.000, -0.408, 0.224, 0.106, 0.866, 0.816, 0.696]])

In [30]:
J_matrix @ xi_1

array([1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000, 1.000])

In [31]:
J_matrix @ xi_2

array([1.000, 1.000, 1.000, -1.000, -1.000, -1.000, -1.000, -1.000,
       -1.000])

# Eigenvalues and eigenvectors for $\bf{J'}$ with $J_{ii}$ set to $0$

In [32]:
w_prime, v_prime = np.linalg.eig(J_matrix_hollowed)

In [33]:
w_prime

array([-0.333, 0.667, -0.333, -0.167, 0.833, -0.167, -0.167, -0.167,
       -0.167])

In [34]:
v_prime

array([[-0.816, 0.577, 0.201, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.408, 0.577, -0.786, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.408, 0.577, 0.585, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, -0.913, 0.408, -0.429, -0.090, -0.293,
        -0.017],
       [0.000, 0.000, 0.000, 0.183, 0.408, 0.832, 0.278, 0.253, 0.080],
       [0.000, 0.000, 0.000, 0.183, 0.408, -0.017, -0.654, 0.640, -0.098],
       [0.000, 0.000, 0.000, 0.183, 0.408, -0.351, 0.681, 0.261, -0.551],
       [0.000, 0.000, 0.000, 0.183, 0.408, -0.017, -0.108, -0.431,
        -0.211],
       [0.000, 0.000, 0.000, 0.183, 0.408, -0.017, -0.108, -0.431, 0.797]])

In [35]:
J_matrix_hollowed @ xi_1

array([0.667, 0.667, 0.667, 0.833, 0.833, 0.833, 0.833, 0.833, 0.833])

In [36]:
J_matrix_hollowed @ xi_2

array([0.667, 0.667, 0.667, -0.833, -0.833, -0.833, -0.833, -0.833,
       -0.833])